name: portfolio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.1.5
  flutter_svg: ^1.0.0
  animated_text_kit: ^4.2.1
  lottie: ^1.2.1
  card_swiper: ^1.0.4
  hovering: ^1.0.4
  flutter_staggered_animations: ^1.0.0
  delayed_display: ^2.0.0
  url_launcher: ^6.0.18
  confetti: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/logo.png
     - assets/next.png
     - assets/epam.png
     - assets/eflutter.png
     - assets/ejava.png
     - assets/emobile.png
     - assets/ephoto.png
     - assets/evideo.png
     - assets/badge.png
     - assets/gdev.png
     - assets/lendi.png
     - assets/lend.png
     - assets/whats.png
     - assets/goog.png
     - assets/gdevweb.png
     - assets/googlecer.png
     - assets/star.svg
     - assets/carbon.png
     - assets/fluttername.png
     - assets/stack-overflow.svg
     - assets/web-design.png
     - assets/ui.png
     - assets/drew.jpg
     - assets/fchall.jpg
     - assets/one.jpg
     - assets/whitedrew.jpg
     - assets/certificate.jpg
     - assets/javacode.jpg
     - assets/pythoncer.jpg
     - assets/techgoogle.jpg
     - assets/techgithub.jpg
     - assets/techplaystore.jpg
     - assets/quote.jpg
     - assets/call.svg
     - assets/discord.svg
     - assets/facebook.svg
     - assets/github.svg
     - assets/gmail.svg
     - assets/playgoogle.svg
     - assets/instagram.svg
     - assets/linkedin.svg
     - assets/youtube.svg
     - assets/playstore.png
     - assets/twitter.svg
     - assets/whatsapp.svg
     - assets/flutter.svg
     - assets/java.svg
     - assets/dart.svg
     - assets/python.svg
     - assets/git.svg
     - assets/gitlab.svg
     - assets/firebase.svg
     - assets/astudio.svg
     - assets/android.svg
     - assets/chart.jpg
     - assets/hello.json
     - assets/project.json
     - assets/programmer.json
     - assets/promote.json
     - assets/google.svg
     - assets/aka.jpg
     - assets/bmi.jpg
     - assets/hub.jpg
     - assets/cred.jpg
     - assets/whatsUI.png
     - assets/unleash.jpg
     - assets/weather.png
     - assets/tdr.jpg
     - assets/todo.jpg
     - assets/news.jpg
     - assets/projectBackground.jpg
     - assets/website.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Spo
       fonts:
         - asset: fonts/Spotify-Dark.ttf
     - family: App
       fonts:
         - asset: fonts/SF-Pro-Display-Regular.otf
     - family: Pop
       fonts:
         - asset: fonts/Poppins-Regular.ttf
     - family: Mon
       fonts:
         - asset: fonts/Montserrat-Medium.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
